// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIx6SuJ0yTg8MuVAMkEQFlunwxf16Vrbk',
    appId: '1:504624694715:android:7f8e9cb93a158cd9ac309e',
    messagingSenderId: '504624694715',
    projectId: 'caloriecare-164c4',
    databaseURL: 'https://caloriecare-164c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'caloriecare-164c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJBsEF6esmzcGAh7ykzxo3JMtiVNwqJfc',
    appId: '1:504624694715:ios:39f0c782780abc38ac309e',
    messagingSenderId: '504624694715',
    projectId: 'caloriecare-164c4',
    databaseURL: 'https://caloriecare-164c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'caloriecare-164c4.firebasestorage.app',
    iosBundleId: 'com.tarumt.myapp.caloriecare',
  );
}
